export const endpoints = {
  auth: {
    login: '/authentications',
    loginQr: '/authentications/qr',
    loginParticipant: '/authentications/participant',
    loginPanitia: '/authentications/panitia',
    refresh: '/authentications',
    logout: '/authentications',
  },
  users: {
    register: '/users',
    me: '/users/me/profile',
    socialProfile: '/users/me/social-profile',
    getById: (id: string) => `/users/${id}`,
    checkInByQr: '/users/check-in/qr',
    search: '/users/search',
  },
  sponsors: {
    list: '/sponsors',
  },
  admin: {
    banners: '/admin/banners',
    banner: (id: string) => `/admin/banners/${id}`,
    setGroupLeader: (groupId: string) => `/admin/groups/${groupId}/leader`,
    manualScore: '/admin/scores/manual',
    fieldResults: '/admin/field-results',
    groups: '/admin/groups',
    groupMembers: (groupId: string) => `/admin/groups/${groupId}/members`,
    monitoring: '/admin/monitoring',
    monitoringMissions: '/admin/monitoring/missions',
    barterQueue: '/admin/barter/queue',
    validateBarterStep: (stepId: string) => `/admin/barter/steps/${stepId}/validate`,
    monitoringGroup: (groupId: string) => `/admin/monitoring/${groupId}`,
    accounts: '/admin/accounts',
    finalScores: '/admin/final-scores',
    sheetFinalScores: '/admin/sheets/final-scores',
    submissions: '/admin/submissions',
    submissionScore: (submissionId: string) => `/admin/submissions/${submissionId}/score`,
    accountRole: (userId: string) => `/admin/accounts/${userId}/role`,
    accountRoles: '/admin/accounts/roles',
    accountQrTokens: '/admin/accounts/qr-tokens',
    account: (userId: string) => `/admin/accounts/${userId}`,
    sheetAccountTemplate: '/admin/sheets/accounts/template',
    sheetAccounts: '/admin/sheets/accounts',
    sheetMissionTemplate: '/admin/sheets/missions/template',
    sheetMissions: '/admin/sheets/missions',
    finishBarter: (assignmentId: string) => `/admin/barter/${assignmentId}/finish`,
    exportLeaderboard: '/admin/export/leaderboard',
    participantQrCards: '/admin/participants/qr',
    postScan: '/admin/post/scan',
    postQueue: (missionId: string) => `/admin/post/${missionId}/queue`,
  },
  groups: {
    autoGroup: '/groups/auto-group',
    getById: (groupId: string) => `/groups/${groupId}`,
    updateName: (groupId: string) => `/groups/${groupId}/name`,
    voteLeader: (groupId: string) => `/groups/${groupId}/vote-leader`,
    confirmMember: (groupId: string, targetUserId: string) =>
      `/groups/${groupId}/confirm/${targetUserId}`,
    confirmations: (groupId: string) => `/groups/${groupId}/confirmations`,
    photo: (groupId: string) => `/groups/${groupId}/photo`,
    skipYelYel: (groupId: string) => `/groups/${groupId}/yel-yel/skip`,
  },
  missions: {
    list: '/missions',
    /** Papan misi peserta: pencarian, saringan, dan halaman dihitung server. */
    board: '/missions/board',
    detail: (missionId: string) => `/missions/${missionId}`,
    myAssignments: '/missions/my-assignments',
    myCheckIns: '/missions/my-checkins',
    createAssignment: (missionId: string) => `/missions/${missionId}/assignments`,
    questions: (missionId: string) => `/missions/${missionId}/questions`,
    checkIn: (missionId: string) => `/missions/${missionId}/check-in`,
    checkOut: (missionId: string) => `/missions/${missionId}/check-out`,
    verifyLocation: (missionId: string) => `/missions/${missionId}/verify-location`,
  },
  uploads: {
    create: '/uploads',
  },
  submissions: {
    myGroup: '/submissions/my-group',
    pending: '/submissions/pending',
    history: '/submissions/history',
    pendingCount: '/submissions/pending/count',
    submit: '/submissions',
    validate: (submissionId: string) => `/submissions/${submissionId}/validate`,
    quizReview: (submissionId: string) => `/submissions/${submissionId}/quiz-review`,
    barterStep: '/submissions/barter-steps',
    barterSteps: (assignmentId: string) => `/submissions/barter-steps/${assignmentId}`,
  },
  settings: {
    get: '/settings',
    admin: '/settings/admin',
    releaseMissions: '/settings/admin/release-missions',
    announce: '/settings/admin/announce',
  },
  categories: {
    list: '/group-categories',
    detail: (id: string) => `/group-categories/${id}`,
    assign: '/group-categories/assign',
    distribute: '/group-categories/distribute',
  },
  leaderboard: {
    get: '/leaderboard',
  },
} as const
