export const endpoints = {
  auth: {
    login: '/authentications',
    loginQr: '/authentications/qr',
    refresh: '/authentications',
    logout: '/authentications',
  },
  users: {
    register: '/users',
    me: '/users/me/profile',
    getById: (id: string) => `/users/${id}`,
    checkInByQr: '/users/check-in/qr',
  },
  sponsors: {
    list: '/sponsors',
  },
  admin: {
    banners: '/admin/banners',
    banner: (id: string) => `/admin/banners/${id}`,
    setGroupLeader: (groupId: string) => `/admin/groups/${groupId}/leader`,
    manualScore: '/admin/scores/manual',
    fieldResults: '/admin/field-results',
    groups: '/admin/groups',
    generateGroups: '/admin/groups/generate',
    monitoring: '/admin/monitoring',
    monitoringMissions: '/admin/monitoring/missions',
    barterQueue: '/admin/barter/queue',
    validateBarterStep: (stepId: string) => `/admin/barter/steps/${stepId}/validate`,
    monitoringGroup: (groupId: string) => `/admin/monitoring/${groupId}`,
    accounts: '/admin/accounts',
    accountRole: (userId: string) => `/admin/accounts/${userId}/role`,
    verifyBarter: (assignmentId: string) => `/admin/barter/${assignmentId}/verify`,
    exportLeaderboard: '/admin/export/leaderboard',
  },
  groups: {
    autoGroup: '/groups/auto-group',
    getById: (groupId: string) => `/groups/${groupId}`,
    updateName: (groupId: string) => `/groups/${groupId}/name`,
    voteLeader: (groupId: string) => `/groups/${groupId}/vote-leader`,
    confirmMember: (groupId: string, targetUserId: string) =>
      `/groups/${groupId}/confirm/${targetUserId}`,
    confirmations: (groupId: string) => `/groups/${groupId}/confirmations`,
    photo: (groupId: string) => `/groups/${groupId}/photo`,
  },
  missions: {
    list: '/missions',
    detail: (missionId: string) => `/missions/${missionId}`,
    myAssignments: '/missions/my-assignments',
    myCheckIns: '/missions/my-checkins',
    createAssignment: (missionId: string) => `/missions/${missionId}/assignments`,
    questions: (missionId: string) => `/missions/${missionId}/questions`,
    checkIn: (missionId: string) => `/missions/${missionId}/check-in`,
    checkOut: (missionId: string) => `/missions/${missionId}/check-out`,
  },
  submissions: {
    uploadUrl: '/submissions/upload-url',
    myGroup: '/submissions/my-group',
    pending: '/submissions/pending',
    submit: '/submissions',
    validate: (submissionId: string) => `/submissions/${submissionId}/validate`,
    barterStep: '/submissions/barter-steps',
    barterSteps: (assignmentId: string) => `/submissions/barter-steps/${assignmentId}`,
  },
  settings: {
    get: '/settings',
    admin: '/settings/admin',
    releaseMissions: '/settings/admin/release-missions',
    announce: '/settings/admin/announce',
  },
  leaderboard: {
    get: '/leaderboard',
  },
} as const
